### GENERAL SETTINGS ###

# Site settings
title: Ant solutions
description: "A geek, i ♡ containers, Docker, Golang, Nodejs."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.ant-solutions.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/ant-solutions
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - No 24 Ha Tri 2, Ha Cau
    - Ha Dong, Ha Noi,
    - Viet Nam.
email: nguyentien8x@gmail.com
tel: +84 122-845-6991, +84 169-304-8848


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Tien Nguyen
    position: Full Stack Developer
    text: Tien is founder of the React Viet Nam group where are largest and active ReactJS community in Vietnam. He has five years+ talented full stack developer with a wide range of skills from backend to frontend stack. He is an expert on the following skills JavaScript, C#, MySQL, SQL Server, HTML5, CSS3, OOP, AJAX, jQuery, AngularJS, ReactJS, REST APIs design and implementation, software architecture, etc.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:nguyentien8x@gmail.com
      - title: twitter
        url: http://twitter.com/nhtera
      - title: github
        url: https://github.com/nhtera
  - name: Nam Hoang
    position: Devops & Full Stack Developer
    text: Nam is admin of the React Viet Nam group where are largest and active ReactJS community in Vietnam. He is also a member of the nodejs.org. He has more than five years of experience in software design, development and implementation. Currently he works as a full stack developer and devops at the team. He has strong skill set in JavaScript/Nodejs, ReactJS, REST APIs design and implementation, AWS, Mongodb, Docker, etc.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:particle4dev@gmail.com
      - title: twitter
        url: http://twitter.com/particle4dev
      - title: github
        url: https://github.com/particle4dev
  - name: Anh Hoang
    position: Full Stack Developer
    text: Anh is a Full Stack Developer. He has 5 years of professional (and three more years as hobby) experience in developing mid to large-scale websites and web-applications based on webstandard technologies like JavaScript, C#, MySQL, SQL Server, HTML5, CSS3, OOP, AJAX, jQuery, AngularJS, ReactJS, etc. Anh is a strong team player, works well under pressure and is consumer-focused.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:anh.hta88@gmail.com
      - title: twitter
        url: http://twitter.com/hoanganh_dk
      - title: github
        url: https://github.com/anhht
  - name: Cuong Tran
    position: Devops & Backend Developer
    text: Cuong is admin of the Docker Viet Nam group where are largest and active Docker community in Vietnam. He has five years+ talented full stack developer with a wide range of skills from backend to frontend stack. He is an expert on the following skills JavaScript, Python, C#, MySQL, SQL Server, HTML5, CSS3, OOP, AJAX, jQuery, REST APIs design and implementation, software architecture, etc.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:tranhuucuong91@gmail.com
      - title: twitter
        url: http://twitter.com/tranhuucuong91
      - title: github
        url: https://github.com/tranhuucuong91

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We are ANT Solutions, a team incorporated on December 30th, 2016 by the members who have rich experience in creating software products of high applicability and supplying the same to Japanese, Australia customers."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "One should be so lucky as to work with this team."
    author: "Chung Tran"
    avatar: "//graph.facebook.com/100004112258038/picture?type=small"
    position: CEO - haposoft.com
    site: "http://haposoft.com"